# Generated by Django 5.0.6 on 2024-07-06 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmers_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmerName', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_requested', models.FloatField()),
                ('amount_approved', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField()),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('repayment_date', models.DateTimeField(blank=True, null=True)),
                ('farmers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notifications_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('savings_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saving_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.farmer')),
            ],
        ),
    ]
