# Generated by Django 5.0.6 on 2024-07-08 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.FloatField()),
                ('amount_approved', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField()),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('repayment_date', models.DateTimeField(blank=True, null=True)),
                ('farmer_id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
        ),
    ]
